In [1]:
import pandas as pd

from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split

In [2]:
df = pd.read_csv("../dataset/raw/code_quality.csv")

df.head()

,LOC,CyclomaticComplexity,Methods,Classes,CBO,LCOM,DIT,RFC,NOC,WMC,CommentRatio,MaintainabilityIndex,Quality
0,248,2,48,9,7,28,3,193,1,87,0.37,83,Good
1,198,38,28,2,0,11,4,64,8,78,0.01,45,Poor
2,1136,27,15,15,18,35,1,199,2,90,0.21,34,Poor
3,338,14,49,11,3,11,7,29,5,45,0.30,79,Good
4,960,35,8,13,2,70,5,165,9,47,0.29,46,Poor

In [3]:
encoder = LabelEncoder()

df["Quality"] = encoder.fit_transform(df["Quality"])

df.head()

,LOC,CyclomaticComplexity,Methods,Classes,CBO,LCOM,DIT,RFC,NOC,WMC,CommentRatio,MaintainabilityIndex,Quality
0,248,2,48,9,7,28,3,193,1,87,0.37,83,1
1,198,38,28,2,0,11,4,64,8,78,0.01,45,2
2,1136,27,15,15,18,35,1,199,2,90,0.21,34,2
3,338,14,49,11,3,11,7,29,5,45,0.30,79,1
4,960,35,8,13,2,70,5,165,9,47,0.29,46,2

In [4]:
mapping = dict(zip(encoder.classes_, encoder.transform(encoder.classes_)))

print(mapping)

{'Average': np.int64(0), 'Good': np.int64(1), 'Poor': np.int64(2)}

In [5]:
X = df.drop("Quality", axis=1)

y = df["Quality"]

In [6]:
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.20,
    random_state=42
)

In [7]:
print(X_train.shape)
print(X_test.shape)

(2400, 12)
(600, 12)

In [8]:
processed = pd.concat([X, y], axis=1)

processed.to_csv("../dataset/processed/processed_data.csv",
                 index=False)

In [9]:
print("Preprocessing Completed Successfully")

Preprocessing Completed Successfully

In [10]:
import joblib

joblib.dump(encoder, "../model/label_encoder.pkl")

['../model/label_encoder.pkl']